### ISSUE TITLE
input.fasta needs to be single-line?

### ISSUE THREAD

**Issue by hughcross** [RTRichar/CurateDB#5]
Hello,

I ran the IterRazor.py script on a dataset and got zero results. I noticed that the test file was single line, whereas mine were multi-line (e.g. wrapped at 80 bp). I converted the input sequences to single line fasta, and then it worked. I did not see this mentioned anywhere in the documentation, but I am sorry if I missed it. 

Just in case someone needs it, the awk one-liner I used to convert the fasta file is below (there are lots of solutions out there, but I always end up hunting for it):

```
awk '{if(NR==1) {print $0} else {if($0 ~ /^>/) {print "\n"$0} else {printf $0}}}' input_multiline.fasta > output_oneline.fasta
```

**Comment by RTRichar** [comment]
Hi Hugh, I apologize for the very long delay in my response here. Thanks for pointing out these issues though. I went ahead and added a comment to the Readme about the the fasta formatting and updated the manual. 

Best,
Rodney
