### ISSUE TITLE
versioned release

### ISSUE THREAD

**Issue by dleopold** [RTRichar/CurateDB#6]
I just downloaded the versioned release as shown in the readme and it is not a tar.gz file.

```
(base) ➜  ~ tar xzf MetaCurator-1.0.1.tar.gz

gzip: stdin: not in gzip format
tar: Child returned status 1
tar: Error is not recoverable: exiting now

(base) ➜  ~ file MetaCurator-1.0.1.tar.gz 
MetaCurator-1.0.1.tar.gz: HTML document, UTF-8 Unicode text, with very long lines
```

I am happy to clone the repository at try out MetaCurator that way, but thought you should know.

**Comment by RTRichar** [comment]
Thanks Devin, I had just edited this for another user and didn't realize that the link I copied downloads an html file as opposed to the archive file. Hopefully it is fixed now.
